{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-12-11 17:15:00,221\tINFO trainer.py:1065 -- `_use_trajectory_view_api` only supported for PyTorch so far! Will run w/o.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 118.5/1005.5 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 2/48 CPUs, 0/3 GPUs, 0.0/695.12 GiB heap, 0.0/128.52 GiB objects (0/1.0 accelerator_type:V)<br>Result logdir: /home/smetzger/ray_results/PPO<br>Number of trials: 1/3 (1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">  lr</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_CartPole-v0_748b2_00000</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">0.01</td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-12-11 17:15:00,403\tINFO trainer.py:1065 -- `_use_trajectory_view_api` only supported for PyTorch so far! Will run w/o.\n",
      "2020-12-11 17:15:00,495\tINFO trainer.py:1065 -- `_use_trajectory_view_api` only supported for PyTorch so far! Will run w/o.\n",
      "\u001b[2m\u001b[36m(pid=384841)\u001b[0m 2020-12-11 17:15:02,311\tINFO trainer.py:1065 -- `_use_trajectory_view_api` only supported for PyTorch so far! Will run w/o.\n",
      "\u001b[2m\u001b[36m(pid=384841)\u001b[0m 2020-12-11 17:15:02,311\tINFO trainer.py:619 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=384835)\u001b[0m 2020-12-11 17:15:02,305\tINFO trainer.py:1065 -- `_use_trajectory_view_api` only supported for PyTorch so far! Will run w/o.\n",
      "\u001b[2m\u001b[36m(pid=384835)\u001b[0m 2020-12-11 17:15:02,305\tINFO trainer.py:619 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=384811)\u001b[0m 2020-12-11 17:15:02,333\tINFO trainer.py:1065 -- `_use_trajectory_view_api` only supported for PyTorch so far! Will run w/o.\n",
      "\u001b[2m\u001b[36m(pid=384811)\u001b[0m 2020-12-11 17:15:02,334\tINFO trainer.py:619 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "2020-12-11 17:15:03,774\tERROR trial_runner.py:793 -- Trial PPO_CartPole-v0_748b2_00001: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 726, in _process_trial\n",
      "    result = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 489, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/worker.py\", line 1452, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::PPO.train()\u001b[39m (pid=384835, ip=169.230.190.118)\n",
      "  File \"python/ray/_raylet.pyx\", line 443, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 477, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 481, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 482, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 436, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py\", line 106, in __init__\n",
      "    Trainer.__init__(self, config, env, logger_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 477, in __init__\n",
      "    super().__init__(config, logger_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/trainable.py\", line 249, in __init__\n",
      "    self.setup(copy.deepcopy(self.config))\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 630, in setup\n",
      "    self._init(self.config, self.env_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py\", line 138, in _init\n",
      "    num_workers=self.config[\"num_workers\"])\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 707, in _make_workers\n",
      "    logdir=self.logdir)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py\", line 81, in __init__\n",
      "    lambda p, pid: (pid, p.observation_space, p.action_space)))\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::RolloutWorker.foreach_policy()\u001b[39m (pid=384839, ip=169.230.190.118)\n",
      "  File \"python/ray/_raylet.pyx\", line 443, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 477, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 481, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 482, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 436, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 366, in __init__\n",
      "    self.env = _validate_env(env_creator(env_context))\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 571, in <lambda>\n",
      "    lambda env_context: gym.make(env, **env_context)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 145, in make\n",
      "    return registry.make(id, **kwargs)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 90, in make\n",
      "    env = spec.make(**kwargs)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 60, in make\n",
      "    env = cls(**_kwargs)\n",
      "TypeError: __init__() got an unexpected keyword argument 'corridor_length'\n",
      "2020-12-11 17:15:03,819\tERROR trial_runner.py:793 -- Trial PPO_CartPole-v0_748b2_00002: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 726, in _process_trial\n",
      "    result = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 489, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/worker.py\", line 1452, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::PPO.train()\u001b[39m (pid=384811, ip=169.230.190.118)\n",
      "  File \"python/ray/_raylet.pyx\", line 443, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 477, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 481, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 482, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 436, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py\", line 106, in __init__\n",
      "    Trainer.__init__(self, config, env, logger_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 477, in __init__\n",
      "    super().__init__(config, logger_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/trainable.py\", line 249, in __init__\n",
      "    self.setup(copy.deepcopy(self.config))\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 630, in setup\n",
      "    self._init(self.config, self.env_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py\", line 138, in _init\n",
      "    num_workers=self.config[\"num_workers\"])\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 707, in _make_workers\n",
      "    logdir=self.logdir)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py\", line 81, in __init__\n",
      "    lambda p, pid: (pid, p.observation_space, p.action_space)))\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::RolloutWorker.foreach_policy()\u001b[39m (pid=384828, ip=169.230.190.118)\n",
      "  File \"python/ray/_raylet.pyx\", line 443, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 477, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 481, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 482, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 436, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 366, in __init__\n",
      "    self.env = _validate_env(env_creator(env_context))\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 571, in <lambda>\n",
      "    lambda env_context: gym.make(env, **env_context)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 145, in make\n",
      "    return registry.make(id, **kwargs)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 90, in make\n",
      "    env = spec.make(**kwargs)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 60, in make\n",
      "    env = cls(**_kwargs)\n",
      "TypeError: __init__() got an unexpected keyword argument 'corridor_length'\n",
      "2020-12-11 17:15:03,854\tERROR trial_runner.py:793 -- Trial PPO_CartPole-v0_748b2_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/trial_runner.py\", line 726, in _process_trial\n",
      "    result = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py\", line 489, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/worker.py\", line 1452, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::PPO.train()\u001b[39m (pid=384841, ip=169.230.190.118)\n",
      "  File \"python/ray/_raylet.pyx\", line 443, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 477, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 481, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 482, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 436, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py\", line 106, in __init__\n",
      "    Trainer.__init__(self, config, env, logger_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 477, in __init__\n",
      "    super().__init__(config, logger_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/trainable.py\", line 249, in __init__\n",
      "    self.setup(copy.deepcopy(self.config))\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 630, in setup\n",
      "    self._init(self.config, self.env_creator)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py\", line 138, in _init\n",
      "    num_workers=self.config[\"num_workers\"])\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 707, in _make_workers\n",
      "    logdir=self.logdir)\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/evaluation/worker_set.py\", line 81, in __init__\n",
      "    lambda p, pid: (pid, p.observation_space, p.action_space)))\n",
      "ray.exceptions.RayTaskError(TypeError): \u001b[36mray::RolloutWorker.foreach_policy()\u001b[39m (pid=384836, ip=169.230.190.118)\n",
      "  File \"python/ray/_raylet.pyx\", line 443, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 477, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 481, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 482, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 436, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 366, in __init__\n",
      "    self.env = _validate_env(env_creator(env_context))\n",
      "  File \"/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/ray/rllib/agents/trainer.py\", line 571, in <lambda>\n",
      "    lambda env_context: gym.make(env, **env_context)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 145, in make\n",
      "    return registry.make(id, **kwargs)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 90, in make\n",
      "    env = spec.make(**kwargs)\n",
      "  File \"/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py\", line 60, in make\n",
      "    env = cls(**_kwargs)\n",
      "TypeError: __init__() got an unexpected keyword argument 'corridor_length'\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 118.6/1005.5 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/48 CPUs, 0/3 GPUs, 0.0/695.12 GiB heap, 0.0/128.52 GiB objects (0/1.0 accelerator_type:V)<br>Result logdir: /home/smetzger/ray_results/PPO<br>Number of trials: 3/3 (3 ERROR)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">    lr</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_CartPole-v0_748b2_00000</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">0.01  </td></tr>\n",
       "<tr><td>PPO_CartPole-v0_748b2_00001</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">0.0001</td></tr>\n",
       "<tr><td>PPO_CartPole-v0_748b2_00002</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">1e-06 </td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 3<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                          </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_CartPole-v0_748b2_00000</td><td style=\"text-align: right;\">           1</td><td>/home/smetzger/ray_results/PPO/PPO_CartPole-v0_748b2_00000_0_lr=0.01_2020-12-11_17-15-00/error.txt  </td></tr>\n",
       "<tr><td>PPO_CartPole-v0_748b2_00001</td><td style=\"text-align: right;\">           1</td><td>/home/smetzger/ray_results/PPO/PPO_CartPole-v0_748b2_00001_1_lr=0.0001_2020-12-11_17-15-00/error.txt</td></tr>\n",
       "<tr><td>PPO_CartPole-v0_748b2_00002</td><td style=\"text-align: right;\">           1</td><td>/home/smetzger/ray_results/PPO/PPO_CartPole-v0_748b2_00002_2_lr=1e-06_2020-12-11_17-15-00/error.txt </td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [PPO_CartPole-v0_748b2_00000, PPO_CartPole-v0_748b2_00001, PPO_CartPole-v0_748b2_00002])",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-13-c8fcdff2d91f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m    137\u001b[0m }\n\u001b[1;32m    138\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 139\u001b[0;31m \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtune\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconfig\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstop\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstop\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    140\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    141\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0margs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mas_test\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/cs285/lib/python3.6/site-packages/ray/tune/tune.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, loggers, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint)\u001b[0m\n\u001b[1;32m    432\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    433\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 434\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    435\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    436\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [PPO_CartPole-v0_748b2_00000, PPO_CartPole-v0_748b2_00001, PPO_CartPole-v0_748b2_00002])"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[33m(pid=raylet)\u001b[0m E1211 17:15:03.912735 384694 384694 process.cc:498] Failed to kill process 384839 with error system:3: No such process\n",
      "\u001b[2m\u001b[33m(pid=raylet)\u001b[0m E1211 17:15:03.944334 384694 384694 process.cc:498] Failed to kill process 384828 with error system:3: No such process\n",
      "\u001b[2m\u001b[33m(pid=raylet)\u001b[0m E1211 17:15:03.982443 384694 384694 process.cc:498] Failed to kill process 384836 with error system:3: No such process\n"
     ]
    }
   ],
   "source": [
    "\"\"\"Example of a custom gym environment and model. Run this for a demo.\n",
    "This example shows:\n",
    "  - using a custom environment\n",
    "  - using a custom model\n",
    "  - using Tune for grid search\n",
    "You can visualize experiment results in ~/ray_results using TensorBoard.\n",
    "\"\"\"\n",
    "import argparse\n",
    "import gym\n",
    "from gym.spaces import Discrete, Box\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "import ray\n",
    "from ray import tune\n",
    "from ray.tune import grid_search\n",
    "from ray.rllib.models import ModelCatalog\n",
    "from ray.rllib.models.tf.tf_modelv2 import TFModelV2\n",
    "from ray.rllib.models.tf.fcnet import FullyConnectedNetwork\n",
    "from ray.rllib.models.torch.torch_modelv2 import TorchModelV2\n",
    "from ray.rllib.models.torch.fcnet import FullyConnectedNetwork as TorchFC\n",
    "from ray.rllib.utils.framework import try_import_tf, try_import_torch\n",
    "from ray.rllib.utils.test_utils import check_learning_achieved\n",
    "\n",
    "tf1, tf, tfv = try_import_tf()\n",
    "torch, nn = try_import_torch()\n",
    "\n",
    "# parser = argparse.ArgumentParser()\n",
    "# parser.add_argument(\"--run\", type=str, default=\"PPO\")\n",
    "# parser.add_argument(\"--torch\", action=\"store_true\")\n",
    "# parser.add_argument(\"--as-test\", action=\"store_true\")\n",
    "# parser.add_argument(\"--stop-iters\", type=int, default=50)\n",
    "# parser.add_argument(\"--stop-timesteps\", type=int, default=100000)\n",
    "# parser.add_argument(\"--stop-reward\", type=float, default=0.1)\n",
    "\n",
    "\n",
    "class SimpleCorridor(gym.Env):\n",
    "    \"\"\"Example of a custom env in which you have to walk down a corridor.\n",
    "    You can configure the length of the corridor via the env config.\"\"\"\n",
    "\n",
    "    def __init__(self, config):\n",
    "        self.end_pos = config[\"corridor_length\"]\n",
    "        self.cur_pos = 0\n",
    "        self.action_space = Discrete(2)\n",
    "        self.observation_space = Box(\n",
    "            0.0, self.end_pos, shape=(1, ), dtype=np.float32)\n",
    "\n",
    "    def reset(self):\n",
    "        self.cur_pos = 0\n",
    "        return [self.cur_pos]\n",
    "\n",
    "    def step(self, action):\n",
    "        assert action in [0, 1], action\n",
    "        if action == 0 and self.cur_pos > 0:\n",
    "            self.cur_pos -= 1\n",
    "        elif action == 1:\n",
    "            self.cur_pos += 1\n",
    "        done = self.cur_pos >= self.end_pos\n",
    "        return [self.cur_pos], 1.0 if done else -0.1, done, {}\n",
    "\n",
    "\n",
    "class CustomModel(TFModelV2):\n",
    "    \"\"\"Example of a keras custom model that just delegates to an fc-net.\"\"\"\n",
    "\n",
    "    def __init__(self, obs_space, action_space, num_outputs, model_config,\n",
    "                 name):\n",
    "        super(CustomModel, self).__init__(obs_space, action_space, num_outputs,\n",
    "                                          model_config, name)\n",
    "        self.model = FullyConnectedNetwork(obs_space, action_space,\n",
    "                                           num_outputs, model_config, name)\n",
    "        self.register_variables(self.model.variables())\n",
    "\n",
    "    def forward(self, input_dict, state, seq_lens):\n",
    "        return self.model.forward(input_dict, state, seq_lens)\n",
    "\n",
    "    def value_function(self):\n",
    "        return self.model.value_function()\n",
    "\n",
    "\n",
    "class TorchCustomModel(TorchModelV2, nn.Module):\n",
    "    \"\"\"Example of a PyTorch custom model that just delegates to a fc-net.\"\"\"\n",
    "\n",
    "    def __init__(self, obs_space, action_space, num_outputs, model_config,\n",
    "                 name):\n",
    "        TorchModelV2.__init__(self, obs_space, action_space, num_outputs,\n",
    "                              model_config, name)\n",
    "        nn.Module.__init__(self)\n",
    "\n",
    "        self.torch_sub_model = TorchFC(obs_space, action_space, num_outputs,\n",
    "                                       model_config, name)\n",
    "\n",
    "    def forward(self, input_dict, state, seq_lens):\n",
    "        input_dict[\"obs\"] = input_dict[\"obs\"].float()\n",
    "        fc_out, _ = self.torch_sub_model(input_dict, state, seq_lens)\n",
    "        return fc_out, []\n",
    "\n",
    "    def value_function(self):\n",
    "        return torch.reshape(self.torch_sub_model.value_function(), [-1])\n",
    "\n",
    "import sys\n",
    "sys.argv = ['-f']\n",
    "parser = argparse.ArgumentParser()\n",
    "parser.add_argument(\"--run\", type=str, default=\"PPO\")\n",
    "parser.add_argument(\"--torch\", action=\"store_true\")\n",
    "parser.add_argument(\"--as-test\", action=\"store_true\")\n",
    "parser.add_argument(\"--stop-iters\", type=int, default=50)\n",
    "parser.add_argument(\"--stop-timesteps\", type=int, default=100000)\n",
    "parser.add_argument(\"--stop-reward\", type=float, default=0.1)\n",
    "args = parser.parse_args()\n",
    "\n",
    "\n",
    "# Can also register the env creator function explicitly with:\n",
    "# register_env(\"corridor\", lambda config: SimpleCorridor(config))\n",
    "ModelCatalog.register_custom_model(\n",
    "    \"my_model\", TorchCustomModel if args.torch else CustomModel)\n",
    "\n",
    "config = {\n",
    "    \"env\":'CartPole-v0', # SimpleCorridor,  # or \"corridor\" if registered above\n",
    "    \"env_config\": {\n",
    "        \"corridor_length\": 5,\n",
    "    },\n",
    "    # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.\n",
    "    \"num_gpus\": int(os.environ.get(\"RLLIB_NUM_GPUS\", \"0\")),\n",
    "    \"model\": {\n",
    "        \"custom_model\": \"my_model\",\n",
    "    },\n",
    "    \"vf_share_layers\": True,\n",
    "    \"lr\": grid_search([1e-2, 1e-4, 1e-6]),  # try different lrs\n",
    "    \"num_workers\": 1,  # parallelism\n",
    "    \"framework\": \"torch\" if args.torch else \"tf\",\n",
    "}\n",
    "\n",
    "stop = {\n",
    "    \"training_iteration\": args.stop_iters,\n",
    "    \"timesteps_total\": args.stop_timesteps,\n",
    "    \"episode_reward_mean\": args.stop_reward,\n",
    "}\n",
    "\n",
    "results = tune.run(args.run, config=config, stop=stop)\n",
    "\n",
    "if args.as_test:\n",
    "    check_learning_achieved(results, args.stop_reward)\n",
    "ray.shutdown()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
